### PR TITLE
Updated composer dependencies

### PR DESCRIPTION
**Pull request by Progi1984**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fixed PHPStan errors
| Type?             | enhancement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Github Actions are :green_circle: 

## Dev Dependencies
* `composer/semver` : `3.2.4` to `3.2.5`
* `composer/xdebug-handler` : `1.4.5` to `2.0.2`
* `doctrine/annotations` : `1.11.1` to `1.13.2`
* `friendsofphp/php-cs-fixer` : `2.16.7` to `2.19.2`
* `prestashop/header-stamp` : `1.6` to `1.7`
* `prestashop/php-dev-tools` : `3.10` to `3.16`
* `psr/container` : `1.0.0` to `1.1.1`
* `psr/log` : `1.1.3` to `1.1.4`
* `squizlabs/php_codesniffer` : `3.5.8` to `3.6.0`
* `symfony/deprecation-contracts` : `2.2.0` to `2.4.0`
* `symfony/event-dispatcher` : `5.1.8` to `5.3.7`
* `symfony/event-dispatcher-contracts` : `2.2.0` to `2.4.0`
* `symfony/filesystem` : `5.1.8` to `5.3.4`
* `symfony/finder` : `5.1.8` to `3.4.47`
* `symfony/options-resolver` : `5.1.8` to `5.3.7`
* `symfony/polyfill-ctype` : `1.20.0` to `1.23.0`
* `symfony/polyfill-mbstring` : `1.20.0` to `1.23.1`
* `symfony/polyfill-php72` : `1.20.0` to `1.23.0`
* `symfony/polyfill-php73` : `1.20.0` to `1.23.0`
* `symfony/polyfill-php80` : `1.20.0` to `1.23.1`
* `symfony/process` : `5.1.8` to `5.3.7`
* `symfony/service-contracts` : `2.2.0` to `2.4.0`
* `symfony/stopwatch` : `5.1.8` to `5.3.4`

### CODE REVIEW

**Review by matks — APPROVED** [review]
PR is good :)

Maybe it would help maintainers review if you list the dependencies version changes in the PR body 😉

**Comment by Progi1984** [comment]
@matks Done

**Review by matks — COMMENTED** [review]
I might be wrong but there seems to be only composer.lock changes in this PR, no composer.json.

And composer.lock contains more:
- composer/semver: 3.2.4 to 3.2.5
- symfony/console: v5.1.8 to v3.4.47
...

**Comment by Progi1984** [comment]
@matks Oh sorry. I thought direct dependencies and not dependencies of dependencies, or dependencies of dependencies of dependencies.

[EDIT] Done

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
> I might be wrong but there seems to be only composer.lock changes in this PR, no composer.json.
> 
> And composer.lock contains more:
> 
> * composer/semver: 3.2.4 to 3.2.5
> * symfony/console: v5.1.8 to v3.4.47
>   ...

That's the exact reason why I love when we also update composer.json when updating dependencies for better understanding

**Comment by PierreRambaud** [comment]
Thank you @Progi1984

**Pull request merged**
